apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-management-ingress
  annotations:
    kubernetes.io/ingress.class: "alb" # AWS Application Load Balancer Ingress Controller
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: project-management-service
            port:
              number: 80
